# Generated by Django 3.1 on 2020-08-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaya_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='bed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
